# Generated by Django 4.1.5 on 2023-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="stu_fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_id", models.IntegerField()),
                ("fee_status", models.TextField()),
                ("fee", models.IntegerField()),
            ],
        ),
    ]
